name: android-llvm-msvc-build

permissions:
  contents: write
  
on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      BUILD_TYPE: Release
    steps:

- name: Setup build deps
  run: |
    sudo apt-get update
    sudo apt-get install -y build-essential make cmake ninja-build p7zip-full p7zip-rar \
      gcc-11 g++-11 libstdc++-11-dev-arm64-cross

- name: Build llvm
  run: |
    find llvm-msvc/llvm -type f -exec sed -i 's/#include <vcruntime_string\.h>/\/\/ #include <vcruntime_string.h>/g' {} +
    cmake -GNinja -B build \
      -DCMAKE_INSTALL_PREFIX=install \
      -DLLVM_INCLUDE_TESTS=OFF \
      -DLLVM_INCLUDE_EXAMPLES=OFF \
      -DLLVM_ENABLE_ASSERTIONS=OFF \
      -DLLDB_ENABLE_PYTHON=OFF \
      -DLLVM_ENABLE_LIBXML2=OFF \
      -DLLVM_ENABLE_ZLIB=OFF \
      -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
      -DLLVM_TARGET_ARCH=AArch64 \
      -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64;RISCV" \
      -DLLVM_ENABLE_PROJECTS="clang;lld;lldb" \
      -DLLVM_HOST_TRIPLE="x86_64-pc-linux-gnu" \
      -DLLVM_TARGET_TRIPLE="aarch64-linux-gnu" \
      -DLLVM_DEFAULT_TARGET_TRIPLE="aarch64-linux-gnu" \
      llvm-msvc/llvm
    cmake --build build --config ${{ env.BUILD_TYPE }}
    cmake --build build --config ${{ env.BUILD_TYPE }} --target install

- name: Package llvm
  run: |
    ls -lah
    ls -lah install || true
    7z a android-llvm-msvc.zip install
    ls -lah android-llvm-msvc.zip

- name: Upload Artifact
  uses: actions/upload-artifact@v4
  with:
    name: android-llvm-msvc
    path: android-llvm-msvc.zip
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: android-llvm-msvc.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
